<?php
/**
 * @var \Dariam\RegularCustomer\Block\Product\View\RegularCustomerRequest $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div class="form dariam-regular-customer-form-wrapper" data-bind="scope: 'regularCustomerRequest'">
    <?= $block->getChildHtml('dariam.regular.customer.form.extras') ?>
    <hr>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
        }
    }
</script>
