<?php
/**
 * @var \Dariam\RegularCustomer\Block\Product\View\RegularCustomerRequest $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div class="dariam-regular-customer-request">
    <form class="form"
          id="dariam-regular-customer-form"
          action="<?= $escaper->escapeHtmlAttr($block->getData('request_submit_url')) ?>"
          method="post"
          style="float: left;width: 40%;"
    >
        <fieldset class="fieldset">
            <legend class="legend">
                <span><?= $escaper->escapeHtml(__('Loyalty program for Regular Customers')) ?></span>
            </legend>
            <?= $block->getChildHtml('dariam.regular.customer.message') ?>
            <hr>
            <div class="field name required">
                <label class="label" for="name">
                    <span><?= $escaper->escapeHtml(__('Firstname')) ?></span>
                </label>
                <div class="control">
                    <input name="name"
                           title="<?= $escaper->escapeHtmlAttr(__('Firstname')) ?>"
                           class="input-text"
                           type="text"
                    />
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email">
                    <span><?= $escaper->escapeHtml(__('Email')) ?></span>
                </label>
                <div class="control">
                    <input name="email"
                           title="<?= $escaper->escapeHtmlAttr(__('Email')) ?>"
                           class="input-text"
                           type="email"
                    />
                </div>
            </div>
        </fieldset>
        <div class="actions-toolbar">
            <div class="primary">
                <?php if ($product = $block->getData('product')) : ?>
                    <input type="hidden"
                           name="product_id"
                           value="<?= $escaper->escapeHtmlAttr((int) $product->getId()) ?>"
                    />
                <?php endif; ?>
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr(__('Send Request')) ?>"
                        class="action submit primary"
                >
                    <span><?= $escaper->escapeHtml(__('Send Request')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>
