<?php
/**
 * @var \Dariam\RegularCustomer\Block\Product\View\RegularCustomerRequest $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<div class="form dariam-regular-customer-form" data-bind="scope: 'regularCustomerRequestForm'">
    <?= $block->getChildHtml('dariam.regular.customer.form.extras') ?>
    <hr>
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "regularCustomerRequestForm": {
                        "component": "Dariam_RegularCustomer_form",
                        "action": "<?= $block->getData('request_submit_url') ?>",
                        "productId": <?= (int) $block->getProduct()->getId() ?>,
                        "isModal": <?= $block->getData('form_is_modal') ? 'true' : 'false' ?>
                    }
                }
            }
        }
    }
</script>
