<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
?>
<h2>Thank you for submission!</h2>
<p>Your vendor is <strong><?= $escaper->escapeHtml($block->getRequest()->getParam('vendor', 'Not set')) ?></strong>.</p>
<p>Your module is <strong><?= $escaper->escapeHtml($block->getRequest()->getParam('module', 'Not set')) ?></strong>.</p>
