<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<ul>
    <li>
        <a href="<?= $block->getUrl('dariam-controller-demos/demos/redirectresponsedemo') ?>" target="_blank">RedirectResponseDemo</a>
    </li>
    <li>
        <a href="<?= $block->getUrl('dariam-controller-demos/demos/formresponsedemo', ['vendor' => 'Dariam', 'module' => 'ControllerDemos']) ?>">JsonResponseDemo</a>
    </li>
    <li>
        <a href="<?= $block->getUrl('dariam-controller-demos/demos/forwardresponsedemo', ['vendor' => 'Dariam', 'module' => 'ControllerDemos']) ?>">ForwardResponseDemo</a>
    </li>
</ul>
<form method="GET" action="<?= $block->getUrl('dariam-controller-demos/demos/formresponsedemo') ?>">
    <label>
        Vendor
        <input type="text" name="vendor" value="Dariam">
    </label>
    <label>
        Module
        <input type="text" name="module" value="ControllerDemos">
    </label>
    <button type="submit">Submit</button>
</form>
